model = "gpt-5.1"
model_reasoning_effort = "medium"
model_reasoning_summary = "detailed"

[projects."/data1/huangzhe/code/edge10-quant"]
trust_level = "trusted"

[projects."/data1/huangzhe/code/Synthetic-Video-Pipeline"]
trust_level = "trusted"

[projects."/data2/huangzhe/code/llm-perf-opt"]
trust_level = "trusted"

[projects."/data2/huangzhe/code/Synthetic-Video-Pipeline"]
trust_level = "trusted"

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

[mcp_servers.tavily]
command = "npx"
args = ["-y", "tavily-mcp"]
env = { "TAVILY_API_KEY" = "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" }

[notice]
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true
